# Generated by Django 4.0.5 on 2022-06-29 17:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garanter',
            name='id_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='garanter',
            name='mpesa_statements',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
