# Generated by Django 4.0.5 on 2022-06-29 17:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_garanter_id_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
