# Generated by Django 4.0.5 on 2022-06-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AlterField(
            model_name='modulesubscribe',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
